* README.org
Hacer un readme.org para leer cada vez que regrese de vacaciones incluyendo la
organización de los archivos de esta computadora y otras.
* Financiero
** Banco
- calcular gastos del viaje
** Vector
- Mirar
- Cmx.CPO
* [#A] DRAFT! 
* DONE Comparación
- sacar la gráfica de dirección de emision para marton 
* Evaluación
escribir lo de la evalación de frank
** 1: Review of the past reference period
During this period I familiarized myself with the code Synrad3D developed at
CLASSE by David Sagan. This code is used to simulate the emission of synchrotron
radiation and tracks its photons inside the accelerators vacuum chamber through
all reflections until absorption.
I attended MePAS in 2015 and also  attended JUAS in 2016
I used Synrad3D to analyze the behavior of synchrotron radiation in the arcs of
LHC and draw a 3D map of the absorption points in a realistic model (including
the sawtooth pattern on the external side of the wall) 
Afterwards I made a similar map for ATS optics baseline for HL-LHC and compared
the way radiation behaves between the FlatHS and Round versions of the optics. I
attended IPAC'16 and gave an oral presentation on the results of this simulations.
I made a model to match the geometry of a proposed vacuum chamber for FCC-hh to
work as a first approximation. This model was used to show the efficiency of the
size of the slits in said chamber at baseline energy. I also ran several
simulations at different energies to see at which point it is convenient to use
the slits. The results from this will be particularly helpful for deciding what
is the best option for HE-LHC vacuum chamber.   
** 2: Review of the next reference period
On the following months I will be working on simulations for HE-LHC and FCC-hh
projects. This results should be submitted for consideration for FCC Week 2017. 
We will compare the results of the simulations in Synrad3D with results from
Synrad+ (developed at CERN by R. Kersevan) and also I will compare our LHC 
simulations to actual measurements done on the vacuum chamber.
The results from this comparisons will be presented at IPAC'17.
And finally I will sort the results to get them published in a journal.

** 3: Publications 
https://weblib.cern.ch/record/2159686/files/CERN-ACC-2016-0079.pdf
* TODO [#A] set APS format to org-eport
* Bicicleta
hacer el request en el EDH
* Leer lo de gonzalo
- impreso y encarpoetado
* inicar el paper
* Ver que onda con cemex
* Hablar a vector
que me reactiben la cuenta
* BMAD
revisar un poco del código para en un futuro meterse al código del synrad3d
* efectos de soldadura
en donde se acaba cada tubo del beam pipe, cómo está la junta?
en caso de ser soldada, puede tener rebabas que hagan que la luz se absorba
justo ahi o algo asi
